// Topics offered as suggestions in the Topics tab, grouped so a long list
// stays browsable. Shared with the browser: pure data, nothing else.
//
// These are only starting points. A topic is free text and relevance is
// judged semantically, so anything a reader types works just as well.

export const SUGGESTED_TOPIC_GROUPS = [
  {
    name: "AI",
    topics: [
      "AI",
      "AI agents",
      "OpenAI",
      "Anthropic",
      "Google DeepMind",
      "Large language models",
      "AI regulation",
      "AI chips",
      "Open-source AI",
      "AI in medicine",
      "Computer vision",
      "Robotics",
      "Self-driving cars",
    ],
  },
  {
    name: "Software",
    topics: [
      "Next.js",
      "React",
      "JavaScript",
      "TypeScript",
      "Python",
      "Rust",
      "Web development",
      "Mobile development",
      "Databases",
      "DevOps",
      "Cloud computing",
      "Cybersecurity",
      "Open source",
      "Developer tools",
    ],
  },
  {
    name: "Technology",
    topics: [
      "Technology",
      "Apple",
      "Google",
      "Microsoft",
      "Meta",
      "Amazon",
      "Nvidia",
      "Semiconductors",
      "Consumer electronics",
      "Quantum computing",
      "Telecoms",
      "Privacy",
      "Social media",
    ],
  },
  {
    name: "Business",
    topics: [
      "Startups",
      "SaaS",
      "Venture capital",
      "Funding rounds",
      "Mergers and acquisitions",
      "Entrepreneurship",
      "Remote work",
      "Marketing",
      "E-commerce",
      "Supply chains",
      "Retail",
      "Aviation",
    ],
  },
  {
    name: "Finance",
    topics: [
      "Finance",
      "Stock markets",
      "Interest rates",
      "Inflation",
      "Central banks",
      "Cryptocurrency",
      "Bitcoin",
      "Housing market",
      "Personal finance",
      "Taxes",
      "Pensions",
    ],
  },
  {
    name: "World",
    topics: [
      "World news",
      "Politics",
      "Elections",
      "European Union",
      "Geopolitics",
      "Defence",
      "Immigration",
      "Human rights",
      "Law and courts",
      "Corruption",
      "Local news",
    ],
  },
  {
    name: "Science",
    topics: [
      "Science",
      "Space exploration",
      "Astronomy",
      "Physics",
      "Biology",
      "Genetics",
      "Neuroscience",
      "Archaeology",
      "Mathematics",
      "Psychology research",
      "Oceans",
    ],
  },
  {
    name: "Health",
    topics: [
      "Health",
      "Medicine",
      "Mental health",
      "Nutrition",
      "Fitness",
      "Sleep",
      "Public health",
      "Pharmaceuticals",
      "Longevity",
      "Healthcare policy",
    ],
  },
  {
    name: "Climate",
    topics: [
      "Climate change",
      "Renewable energy",
      "Solar power",
      "Wind power",
      "Nuclear energy",
      "Electric vehicles",
      "Energy prices",
      "Sustainability",
      "Wildfires",
      "Agriculture",
      "Water",
    ],
  },
  {
    name: "Culture",
    topics: [
      "Culture",
      "Film",
      "Television",
      "Music",
      "Books",
      "Art",
      "Design",
      "Architecture",
      "Photography",
      "Travel",
      "Food",
      "Fashion",
    ],
  },
  {
    name: "Sport",
    topics: [
      "Football",
      "Formula 1",
      "Tennis",
      "Basketball",
      "Cycling",
      "Athletics",
      "Olympics",
      "Rugby",
      "Golf",
      "Motorsport",
    ],
  },
  {
    name: "Gaming",
    topics: [
      "Gaming",
      "Game development",
      "Esports",
      "PlayStation",
      "Xbox",
      "Nintendo",
      "PC gaming",
      "Indie games",
      "Virtual reality",
    ],
  },
  {
    name: "Work",
    topics: [
      "Productivity",
      "Time management",
      "Habits",
      "Focus",
      "Note-taking",
      "Learning",
      "Career",
      "Leadership",
      "Hiring",
      "Education",
    ],
  },
];

/** Every suggestion, flat, in group order. */
export const SUGGESTED_TOPICS = SUGGESTED_TOPIC_GROUPS.flatMap((g) => g.topics);
